#!/usr/bin/env bash
# BoxedVN - build Wine's x86-64 OSS audio driver (wineoss.drv + wineoss.so).
#
# Ubuntu does not build this driver. Wine's configure gates dlls/wineoss.drv
# on <sys/soundcard.h>, which Ubuntu does not ship, so the amd64 libwine
# package carries winealsa and winepulse instead -- and neither of those can
# work inside BoxedWine: winepulse wants a PulseAudio daemon on a unix socket
# and winealsa wants /dev/snd, and the guest kernel emulates neither.
# wineoss talks to /dev/dsp and /dev/mixer with raw ioctls, which BoxedWine
# has emulated for the IA-32 lane since forever. See docs/PLAN_X64_AUDIO.md.
#
# The version has to match the installed amd64 libwine. Wine's PE/unix driver
# boundary (__wine_unix_call) is a private, unversioned interface: a
# wineoss.so from a different Wine version paired with the packaged
# mmdevapi.dll is undefined behaviour, not a degraded experience. Pass
# --wine-version with the UPSTREAM version of the installed package (Ubuntu's
# "9.0~repack-4build3" is upstream 9.0).
#
# Usage:
#   scripts/build-wine64-oss-driver.sh --output-dir DIR \
#       [--wine-version 9.0] [--wine-source DIR] [--jobs N]

source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/common.sh"

OUTPUT_DIR=""
WINE_VERSION=""
WINE_SOURCE=""
JOBS=""
usage() { sed -n '2,21p' "${BASH_SOURCE[0]}" | sed 's/^# \{0,1\}//'; }
while [[ $# -gt 0 ]]; do
    case "$1" in
        --output-dir)   [[ $# -ge 2 ]] || die "--output-dir needs a value"
                        OUTPUT_DIR="$2"; shift 2 ;;
        --wine-version) [[ $# -ge 2 ]] || die "--wine-version needs a value"
                        WINE_VERSION="$2"; shift 2 ;;
        --wine-source)  [[ $# -ge 2 ]] || die "--wine-source needs a value"
                        WINE_SOURCE="$2"; shift 2 ;;
        --jobs)         [[ $# -ge 2 ]] || die "--jobs needs a value"
                        JOBS="$2"; shift 2 ;;
        -h|--help)      usage; exit 0 ;;
        *)              die "Unknown argument '$1'. Run with --help." ;;
    esac
done

[[ -n "${OUTPUT_DIR}" ]] || die "--output-dir is required."
[[ "$(uname -s)" == "Linux" ]] \
    || die "This builder must run on Linux: the unix half of a Wine driver is an ELF shared object for the guest's host architecture."
[[ -n "${WINE_VERSION}" || -n "${WINE_SOURCE}" ]] \
    || die "Pass --wine-version (the upstream version of the installed amd64 libwine) or --wine-source (an unpacked Wine tree of that version)."

require_command bison
require_command curl
require_command file
require_command flex
require_command gcc
require_command make
require_command tar
# Wine 9.0 builds its PE modules with a mingw cross compiler. Without one,
# configure still succeeds but produces a fake PE module built from the unix
# object, which is not what the guest's loader can map.
require_command x86_64-w64-mingw32-gcc \
    "Install it with 'sudo apt-get install -y gcc-mingw-w64-x86-64'; Wine builds its PE modules with a mingw cross compiler and silently degrades without one."

[[ -n "${JOBS}" ]] || JOBS="$(nproc 2>/dev/null || echo 2)"
mkdir -p "${OUTPUT_DIR}"
OUTPUT_DIR="$(cd "${OUTPUT_DIR}" && pwd)"

WORK="${BOXEDVN_THIRD_PARTY}/wine-oss"
mkdir -p "${WORK}"

# --- the OSS header ---------------------------------------------------------
#
# Wine needs <sys/soundcard.h>. glibc stopped shipping it, but Ubuntu's
# linux-libc-dev still installs <linux/soundcard.h>, which IS the OSSv4 header
# -- the kernel's copy carries oss_sysinfo, oss_audioinfo, SNDCTL_SYSINFO,
# SNDCTL_AUDIOINFO and SNDCTL_ENGINEINFO, which are exactly the OSSv4 pieces
# dlls/wineoss.drv/oss.c uses for enumeration. So the shim is the one-line
# wrapper glibc used to ship, and it is checked rather than assumed: if the
# kernel header ever loses one of those names, this fails here by name instead
# of producing a driver that cannot enumerate a device.
OSS_INCLUDE="${WORK}/oss-include"
mkdir -p "${OSS_INCLUDE}/sys"
cat > "${OSS_INCLUDE}/sys/soundcard.h" <<'EOF'
/* Generated by scripts/build-wine64-oss-driver.sh.
 *
 * glibc used to ship exactly this wrapper. Wine's configure gates
 * dlls/wineoss.drv on the presence of <sys/soundcard.h>; the kernel's
 * <linux/soundcard.h> is the OSSv4 header the driver actually needs.
 */
#ifndef _BOXEDVN_SYS_SOUNDCARD_H
#define _BOXEDVN_SYS_SOUNDCARD_H
#include <linux/soundcard.h>
#endif
EOF

log "Checking the OSSv4 symbols wineoss needs"
OSS_PROBE="${WORK}/oss-probe.c"
cat > "${OSS_PROBE}" <<'EOF'
#include <sys/soundcard.h>
oss_sysinfo boxedvn_sysinfo;
oss_audioinfo boxedvn_audioinfo;
int boxedvn_requests[] = {
    SNDCTL_SYSINFO, SNDCTL_AUDIOINFO, SNDCTL_ENGINEINFO,
    SNDCTL_DSP_SETFMT, SNDCTL_DSP_SPEED, SNDCTL_DSP_CHANNELS,
    SNDCTL_DSP_GETOSPACE, SNDCTL_DSP_GETISPACE,
};
int boxedvn_caps = PCM_CAP_OUTPUT;
int main(void) { return 0; }
EOF
gcc -I"${OSS_INCLUDE}" -o "${WORK}/oss-probe" "${OSS_PROBE}" \
    || die "<linux/soundcard.h> does not provide the OSSv4 declarations wineoss needs (oss_sysinfo, oss_audioinfo, SNDCTL_SYSINFO, SNDCTL_AUDIOINFO, SNDCTL_ENGINEINFO). Install linux-libc-dev, or supply a real OSS <sys/soundcard.h> as docs/How-To-Build-Wine-FileSystem.md step 4 describes."
ok "OSSv4 declarations available"

# --- the Wine source --------------------------------------------------------
if [[ -z "${WINE_SOURCE}" ]]; then
    WINE_SOURCE="${WORK}/wine-${WINE_VERSION}"
    if [[ ! -d "${WINE_SOURCE}" ]]; then
        tarball="${WORK}/wine-${WINE_VERSION}.tar.xz"
        # The major series directory upstream files releases under: 9.0 and
        # 9.0.1 both live under 9.x.
        series="${WINE_VERSION%%.*}.x"
        if [[ ! -s "${tarball}" ]]; then
            log "Downloading Wine ${WINE_VERSION} sources"
            curl --fail --location --show-error --silent \
                --output "${tarball}.partial" \
                "https://dl.winehq.org/wine/source/${series}/wine-${WINE_VERSION}.tar.xz" \
                || die "Could not download Wine ${WINE_VERSION} from dl.winehq.org. The driver has to be built from the same version as the installed amd64 libwine; pass --wine-source if the tarball must come from elsewhere."
            mv "${tarball}.partial" "${tarball}"
        fi
        log "Unpacking Wine ${WINE_VERSION}"
        tar -xf "${tarball}" -C "${WORK}"
    fi
fi
[[ -d "${WINE_SOURCE}" ]] || die "Wine source directory '${WINE_SOURCE}' does not exist."
WINE_SOURCE="$(cd "${WINE_SOURCE}" && pwd)"
[[ -d "${WINE_SOURCE}/dlls/wineoss.drv" ]] \
    || die "'${WINE_SOURCE}' has no dlls/wineoss.drv. That directory is where Wine's OSS driver lives; this is not a Wine source tree, or it is a version that moved the driver."

# --- configure and build ----------------------------------------------------
#
# Only the one driver is built. Wine's make will build the tools it needs
# (winebuild, widl, ...) and the generated headers on the way, which is a few
# minutes rather than the half hour a full tree takes.
BUILD="${WORK}/build-${WINE_VERSION:-source}"
mkdir -p "${BUILD}"
if [[ ! -s "${BUILD}/Makefile" ]]; then
    log "Configuring Wine (x86_64 only)"
    (
        cd "${BUILD}"
        CPPFLAGS="-I${OSS_INCLUDE}" "${WINE_SOURCE}/configure" \
            --enable-archs=x86_64 \
            --disable-tests \
            --without-x \
            --without-freetype
    ) || die "Wine's configure failed. Its config.log is at ${BUILD}/config.log."
fi

# configure records whether it found the header. A build that got this far
# without it would produce nothing and say nothing, so check the recorded
# answer rather than the eventual absence of a file.
grep -q '^#define HAVE_SYS_SOUNDCARD_H 1' "${BUILD}/include/config.h" \
    || die "Wine's configure did not accept <sys/soundcard.h>, so dlls/wineoss.drv will not be built. See ${BUILD}/config.log."
ok "configure accepted <sys/soundcard.h>"

log "Building dlls/wineoss.drv"
make -C "${BUILD}" -j"${JOBS}" dlls/wineoss.drv \
    || die "Building dlls/wineoss.drv failed."

# --- verify and stage -------------------------------------------------------
unix_half="${BUILD}/dlls/wineoss.drv/wineoss.so"
pe_half="${BUILD}/dlls/wineoss.drv/wineoss.drv"
[[ -s "${unix_half}" ]] \
    || die "The build produced no wineoss.so. Wine's unix half is what talks to /dev/dsp; without it the PE half has nothing to call."
[[ -s "${pe_half}" ]] \
    || die "The build produced no wineoss.drv. Wine's PE half is what mmdevapi loads; without it the unix half is unreachable."
file "${unix_half}" | grep -Eqi 'ELF 64-bit.*x86-64' \
    || die "'${unix_half}' is not an x86-64 ELF shared object."
[[ "$(head -c 2 "${pe_half}")" == "MZ" ]] \
    || die "'${pe_half}' is not a PE image. Wine builds a fake PE module when no mingw cross compiler is available, and the guest loader cannot map one."

cp "${unix_half}" "${OUTPUT_DIR}/wineoss.so"
cp "${pe_half}" "${OUTPUT_DIR}/wineoss.drv"
ok "wineoss.so  -> ${OUTPUT_DIR}/wineoss.so"
ok "wineoss.drv -> ${OUTPUT_DIR}/wineoss.drv"
log "Pass this directory to scripts/build-wine64-runtime-ci.sh with --oss-driver-dir"
