#!/usr/bin/env python3
"""Keep FEX's state-parameter SoftFloat ABI separate from BoxedWine's ABI."""
import argparse
from pathlib import Path
import re
import subprocess


def symbols(source):
    root = source / "External/SoftFloat-3e"
    text = "\n".join(p.read_text(encoding="utf-8") for p in root.rglob("*.[ch]"))
    text = re.sub(r"/\*.*?\*/|//[^\n]*", "", text, flags=re.S)
    names = set(re.findall(
        r"\b((?:softfloat_|(?:extF80|f128|f64|f32|ui64|ui32|i64|i32)_)\w+)\s*(?:\(|\[)", text))
    # Header-only macros have no linker identity, and redefining their names
    # before including the header would defeat the prefix substitution.
    macros = set(re.findall(r"^\s*#\s*define\s+(\w+)", text, re.M))
    names -= macros
    assert "extF80_to_f64" in names and "softfloat_approxRecip_1k0s" in names
    return sorted(names)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("source", type=Path)
    parser.add_argument("header", type=Path)
    parser.add_argument("--verify", nargs="*", type=Path)
    args = parser.parse_args()
    names = symbols(args.source)
    # Rename external declarations, including unresolved helpers, but exclude
    # header-defined primitives unless the CMake target builds them out of line.
    # Inline primitives have internal linkage; renaming their declarations is
    # both unnecessary and rejected by recent Clang versions. Do not use
    # preprocessor aliases: SoftFloat uses #ifndef function_name to select its
    # primitive implementations, so macros would silently remove them.
    root = args.source / "External/SoftFloat-3e"
    selected = re.findall(r"\bsrc/[\w]+\.c\b", (root / "CMakeLists.txt").read_text())
    definitions = "\n".join((root / path).read_text() for path in selected)
    headers = "\n".join(p.read_text() for p in root.rglob("*.h"))
    external = [name for name in names if re.search(
        rf"\b{re.escape(name)}\s*(?:\([^(){{}};]*\)\s*\{{|\[[^]]*\]\s*=)", definitions)
        or not re.search(rf"\b{re.escape(name)}\s*\([^(){{}};]*\)\s*\{{", headers)]
    contents = "// Generated by fex-softfloat-namespace.py; apply to every FEX translation unit.\n#pragma once\n"
    contents += "#ifndef __PRAGMA_REDEFINE_EXTNAME\n#error FEX SoftFloat isolation requires Clang symbol renaming\n#endif\n"
    contents += "".join(f"#pragma redefine_extname {name} boxedvn_fex_{name}\n" for name in external)
    args.header.parent.mkdir(parents=True, exist_ok=True)
    if not args.header.exists() or args.header.read_text(encoding="utf-8") != contents:
        args.header.write_text(contents, encoding="utf-8")
    if args.verify is not None:
        if not args.verify:
            parser.error("--verify requires static archives")
        seen = set()
        for archive in args.verify:
            output = subprocess.check_output(["nm", "-g", str(archive)], text=True)
            for line in output.splitlines():
                fields = line.split()
                if len(fields) >= 2 and len(fields[-2]) == 1:
                    seen.add(fields[-1].removeprefix("_"))
        collisions = seen.intersection(names)
        if collisions:
            raise SystemExit("Unisolated FEX SoftFloat symbols: " + ", ".join(sorted(collisions)))
        if "boxedvn_fex_extF80_to_f64" not in seen:
            raise SystemExit("Missing namespaced FEX conversion symbol")
        print("PASS: FEX references and definitions use isolated SoftFloat symbols")
    print(f"FEX SoftFloat namespace: {len(external)} external symbols")


if __name__ == "__main__":
    main()
