#!/usr/bin/env python3
"""BoxedVN - regenerate the embedded DXBC for the x86-64 Direct3D 11 probe.

The probe draws a cube, which needs a vertex and a pixel shader. Compiling
HLSL inside the guest would put Wine's HLSL compiler between the probe and
the defect under test, so the shaders are compiled here, ahead of time, with
Microsoft's fxc (shader model 4.0) and embedded as byte arrays.

fxc exists only in the Windows SDK, so the generated header is committed and
this script runs on a Windows machine when the HLSL changes. The header
records the SHA-256 of the HLSL it was generated from; the contract test in
test_x64_graphics_probe.py fails when the two drift apart, and also checks
that each blob is a well-formed DXBC container of the recorded length.

Usage:
  python scripts/generate-x64-probe-shaders.py [--fxc PATH]
"""

from __future__ import annotations

import argparse
import glob
import hashlib
import pathlib
import struct
import subprocess
import sys
import tempfile

REPO = pathlib.Path(__file__).resolve().parent.parent
HLSL = REPO / "scripts" / "guest-probes" / "x64-d3d11-cube.hlsl"
HEADER = REPO / "scripts" / "guest-probes" / "x64-d3d11-cube-shaders.h"

SHADERS = (
    # (C identifier, entry point, target profile)
    ("kProbeVertexShader", "vs_main", "vs_4_0"),
    ("kProbePixelShader", "ps_main", "ps_4_0"),
)


def find_fxc(explicit: str | None) -> pathlib.Path:
    if explicit:
        path = pathlib.Path(explicit)
        if not path.is_file():
            raise SystemExit(f"fxc not found at {path}")
        return path
    candidates = sorted(glob.glob(
        r"C:\Program Files (x86)\Windows Kits\10\bin\*\x64\fxc.exe"))
    if not candidates:
        raise SystemExit("fxc.exe not found; install the Windows SDK or pass --fxc")
    return pathlib.Path(candidates[-1])


def compile_shader(fxc: pathlib.Path, entry: str, profile: str) -> bytes:
    with tempfile.TemporaryDirectory() as raw:
        out = pathlib.Path(raw) / f"{entry}.dxbc"
        subprocess.run(
            [str(fxc), "/nologo", "/T", profile, "/E", entry, "/O3",
             "/Fo", str(out), str(HLSL)],
            check=True)
        data = out.read_bytes()
    check_dxbc(data, entry)
    return data


def check_dxbc(data: bytes, name: str) -> None:
    """A DXBC container starts with the magic, a 16-byte digest, a version and
    the total size. Anything else is not something the probe should ship."""
    if len(data) < 32 or data[:4] != b"DXBC":
        raise SystemExit(f"{name}: not a DXBC container")
    total = struct.unpack_from("<I", data, 24)[0]
    if total != len(data):
        raise SystemExit(f"{name}: DXBC size field {total} != {len(data)} bytes")


def format_array(identifier: str, data: bytes) -> str:
    lines = [f"static const BYTE {identifier}[{len(data)}] = {{"]
    for offset in range(0, len(data), 12):
        chunk = data[offset:offset + 12]
        lines.append("    " + ", ".join(f"0x{b:02x}" for b in chunk) + ",")
    lines.append("};")
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--fxc", help="path to fxc.exe")
    args = parser.parse_args(argv)
    fxc = find_fxc(args.fxc)

    source = HLSL.read_bytes()
    digest = hashlib.sha256(source).hexdigest()
    parts = [
        "/*",
        " * BoxedVN - DXBC for the x86-64 Direct3D 11 acceptance probe.",
        " * Copyright (C) 2026 The BoxedWine Team. GPLv2; see license.txt.",
        " *",
        " * GENERATED by scripts/generate-x64-probe-shaders.py from",
        " * x64-d3d11-cube.hlsl with fxc; do not edit by hand.",
        " */",
        "",
        "#ifndef BOXEDVN_X64_D3D11_CUBE_SHADERS_H",
        "#define BOXEDVN_X64_D3D11_CUBE_SHADERS_H",
        "",
        "#include <windows.h>",
        "",
        f'#define BOXEDVN_PROBE_HLSL_SHA256 "{digest}"',
        "",
    ]
    for identifier, entry, profile in SHADERS:
        data = compile_shader(fxc, entry, profile)
        parts.append(f"/* {entry} ({profile}) */")
        parts.append(format_array(identifier, data))
        parts.append("")
        print(f"{identifier}: {len(data)} bytes ({profile} {entry})")
    parts.append("#endif  /* BOXEDVN_X64_D3D11_CUBE_SHADERS_H */")
    parts.append("")
    HEADER.write_text("\n".join(parts), encoding="utf-8", newline="\n")
    print(f"wrote {HEADER.relative_to(REPO)} (hlsl sha256 {digest[:12]})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
